# Global settings
options {
  debug = false
  account-expire = false
  account-expire-duration = 90 # days
  transaction-expire = true
  transaction-expire-duration = 90 # days
  lose-balance-on-death = false
  lose-balance-on-death-amount = 5
}

# Currency settings
currency {
  name = "crowns"
  name-singular = "crown"
  name-plural = "crowns"
  starting-amount = 0
  symbol = ""
  type = "default"
  items {
    gold_ingot = 1
    gold_block = 9
  }
  exp {
    cost = 64 # points
    cooldown = 5000 # ms
  }
}

# Database settings
storage {
  type = "sqlite"
  host = "127.0.0.1"
  port = 3306
  database = "economy"
  username = ""
  password = ""
}