prefix = "<color:#ff7c3b>Economy</color> <white>»</white>"

# Command messages
command-balance-other = "<prefix> <gray><white><name></white> has <yellow><currency></yellow></gray>"
command-balance = "<prefix> <gray>You have <yellow><currency></yellow></gray>"
command-balancetop-header = "<prefix> <gray>Top <count> accounts:</gray>"
command-balancetop-body = " <yellow>›</yellow> <gray><name></gray><reset> <gold>-</gold> <yellow><currency></yellow>"
command-balancetop-footer = "<white>/balance</white> <gray>to view your balance!</gray>"
command-deposit-auto-disable = "<prefix> <gray>Auto deposit has been <red>disabled</red></gray>"
command-deposit-auto-enable = "<prefix> <gray>Auto deposit has been <green>enabled</green></gray>"
command-deposit-auto = "<yellow>+<amount> <currency></yellow>"
command-economy-add = "<prefix> <gray>Added <yellow><currency></yellow> to account '<white><name></white>'</gray>"
command-economy-create = "<prefix> <gray>Created account '<white><name></white>'</gray>"
command-economy-delete = "<prefix> <gray>Deleted account '<white><name></white>'</gray>"
command-economy-freeze = "<prefix> <gray>Froze account '<white><name></white>'</gray>"
command-economy-reload-fail = "<prefix> <red>Config failed to reload, check the console!</red>"
command-economy-reload-success = "<prefix> <gray>Config reloaded successfully</gray>"
command-economy-reset = "<prefix> <gray>Reset the balance of '<white><name></white>'</gray>"
command-economy-set = "<prefix> <gray>Set the balance of '<white><name></white>' to <yellow><currency></yellow></gray>"
command-economy-subtract = "<prefix> <gray>Subtracted <yellow><currency></yellow> from account '<white><name></white>'</gray>"
command-economy-unfreeze = "<prefix> <gray>Unfroze account '<white><name></white>'</gray>"
command-economy-update-fail = "<prefix> <red>Config failed to update, check the console!</red>"
command-economy-update-success = "<prefix> <gray>Config updated successfully</gray>"
command-pay-receive = "<prefix> <gray>You received <yellow><currency></yellow> from <white><name></white></gray>"
command-pay-self = "<prefix> <red>You cannot pay yourself!</red>"
command-pay-send = "<prefix> <gray>Sent <yellow><currency></yellow> to <white><name></white></gray>"

# Error messages
error-account-not-found = "<prefix> <red>Account not found!</red>"
error-not-enough-balance = "<prefix> <red>You do not have enough <currency>!</red>"
error-not-enough-inventory-space = "<prefix> <red>You do not have enough inventory space!</red>"
error-sender-not-player = "<prefix> <red>Only players can use that command!</red>"
error-transaction-failed = "<prefix> <red>Transaction failed</red>"

# Economy messages
economy-death = "<prefix> <red>You died and lost <dark_red><currency></dark_red></red>"
economy-death-killed = "<prefix> <red>You lost <dark_red><currency></dark_red> to <dark_red><killer></dark_red></red>"
economy-death-killer = "<prefix> <gray>You killed <white><player></white> and received <yellow><currency></yellow></gray>"
economy-exp-withdraw = "<prefix> <gray>Converted <yellow><currency></yellow> into <gold><amount> bottles</gold></gray>"
economy-exp-deposit = "<prefix> <gray>Converted <gold><amount> bottles</gold> into <yellow><currency></yellow></gray>"
economy-item-withdraw = "<prefix> <gray>Withdrew <yellow><currency></yellow> from your bank</gray>"
economy-item-deposit = "<prefix> <gray>Deposited <yellow><currency></yellow> into your bank</gray>"